### ISSUE TITLE
[Feature request] Unique NPC skills for characters based on their personalities and interests

### ISSUE THREAD

**Issue by SugarWizard** [purrplingcat/NpcAdventures#143]
I thought about some more abilities for characters. These might need to be re-balanced though ^^'

Elliott 
- Skills based on reading/ writing
- Bard: Elliott inspires the farmer with the tales and legends of old he's read and gives them damage and speed buffs that are slightly stronger than what other characters give. As a trade off he himself is weaker than other adventurers. His buffs start out average but become stronger the more time he spends adventuring (maybe the more monsters are slain in his presence) because he learns more about them.
- Buffs: +3 Attack, +2 Speed - less fighting ability for Elliot - Buffs start out only average

Penny
- Skills based on learning/ nurturing
- Teacher: Penny's knowledge about the local geography increases mining. Her knowledge about the local wildlife increases fishing. Her lack of fighting prowess is offset with having two strong passives in these areas. Maybe can also soothe enemies by befriending them? (see Emily)
- Buffs: +3 Fishing, +2 Mining, - less fighting ability for Penny

Sebastian
- Skills based  on analytical abilities
- Analyst: Sebastian can analyze enemies which increases his critical hit rate and extends  to the farmer. Would also be cool if the critical buff starts out average but continues to become better the more he learns about the enemies, like with Elliot.
- Buffs: +Critical, +1 Speed, +1 Attack (Maybe, depending on how good the critical buff is)

Sam
- Skills based on on the fact that there is an unused weapon "[Sam's Old Guitar" ](https://stardewvalleywiki.com/Sam%27s_Old_Guitar) in the game. I don't know if it's possible but I think it would be fun if this could somehow be incorporated into the mod.
- Musician: Buffs based on the guitar which is a better weapon than the rest of the characters have. Really, anything could be done here.

Emily
- Skills based on spirituality
- ~~Medium: Emily gives higher luck than other characters because she carries Yoba's favor. Can communicate with spirits of the monsters and has a chance to soothe them so they won't attack.~~ **DONE! See `spiritual` skill**
- Buffs: +3 Luck

Shane
- Skills based on living on a farm and being unlucky in life
- Bad Luck: He gives minus luck but as a trade off he is good in in both farming and foraging. the bad luck could also manifest in other ways, like having a chance that a monster is randomly stronger than usual. This would then be needed to be offset with some other good buffs
- Buffs: + 3 Farming, + 3 Foraging, - 1 Luck

**Comment by purrplingcat** [comment]
It looks seems only change buffs for companions. Currently companions has assigned these buffs:
![image](https://user-images.githubusercontent.com/4710267/82552627-c5737580-9b62-11ea-997e-1418ed899523.png)

**Comment by purrplingcat** [comment]
@SugarWizard What do you mean with "Skills based on ..."? How can I compose it to the mod? Btw: skills in mod context is the "powers, proffesions or skill" for the companion like Warrior, Forager, Fighter, Doctor, Scared and etc.

**Comment by purrplingcat** [comment]
It's really big deal, I mark it as *epic* and I take some time for analysis whole problem(s) in this issue and create feature subtickets.

Estimated size: **XL**

**Comment by purrplingcat** [comment]
> Medium: Emily gives higher luck than other characters because she carries Yoba's favor. Can communicate with spirits of the monsters and has a chance to soothe them so they won't attack. 

This proposal was solved with `spiritual` skill which is assigned for Emily.

**Comment by purrplingcat** [comment]
Discontinued
