### ISSUE TITLE
Issues with 1.5 Update

### ISSUE THREAD

**Issue by MoonSylver** [purrplingcat/NpcAdventures#167]
Last night Abigial asked to accompany me when I met her outside the library when it closed. I agreed and  she walked away! BUT the graphics were still up as if she were a companion, even though she never did follow me. Also her indoor portrait popped up when conversing outside (Using Seasonal Villager Outfits). At 10:00 got the standard "It's late, etc." portrait & dialog as if she were with me. Didn't grab a SAMPI log as it was showing no error messages.

Tested it again today. Went to the Pierre's on opening, as soon as I talked to Abigail she split into TWO Abigail's, one who kept walking & one who talked. I let the 2nd one go & "rejoin" the 1st one before asking her to follow. One followed & one stayed behind (though the one who followed DID follow) I DID grab a SAMPI log this time:

https://smapi.io/log/14b2d6dd08a14f3cb3e2264caf2b8f8a

**Comment by CallMeFoxie** [comment]
Hi
I will poke it with a stick. This generally happens when some other mod is messing with NPCs due to the way SDV handles NPCs (ie not global instance but per-map basis and are not unique). Do you happen to have mod installed that changes their behaviour? I am not familiar with most of the mods in that log... and there's nothing suspicious about Abigail in there.

**Comment by MoonSylver** [comment]
> Hi
> I will poke it with a stick. This generally happens when some other mod is messing with NPCs due to the way SDV handles NPCs (ie not global instance but per-map basis and are not unique). Do you happen to have mod installed that changes their behaviour? I am not familiar with most of the mods in that log... and there's nothing suspicious about Abigail in there.

Hm. Not that I'm _aware_ of...I run a LOT of mod's, but they're all ones that had dialog, seasonal outfits, New NPC's & Locations, More crops & recipies, etc, etc, etc. Only ones I can think of that change NPC Behavior Is Social Haley & Social George, & Immersive Spouses, all of which alter schedules a bit, but none of which would apply here. Only Abigail specific one I have is a Dialog one.

Never had problems before, & I've played quite a bit with NPC Adventures, maybe 100 hrs or more. Just started w/ the 1.5 update, but it could always be one of the other mods that have been updated I imagine.

Can try with some other NPC's & see what happens.

**Comment by MoonSylver** [comment]
So I managed to successfully recruit all NPC's that I had enough Hearts for: Emily, Haley, Leah, & Jade (Custom NPC), with no issue. Tried to recruit Abby, she was in her room on the "Still can't beat the Prairie King" dialog (don't know if that's a recruit-able moment  or not).

Canceled the day & tried again. Went to store on opening & got it to duplicate Abby again. Did no recruit & left. The Duplicate even remained if I left the store & came back. Recruited one & left, released her, & went back, both remained.

Canceled the day & waited until later in the day when she left the store & was standing on the bridge, but still got the duplicate bug.

Here is another SMAPI log:

https://smapi.io/log/1bccd94a87e543a0bf0bb5e92ae40155

Only difference between Abby and the others I can think of is A) She's at 10 hearts, B) she is my Girlfriend  & C) the dialog mod "Abigail Loves You". Have not been able to replicate the error with anyone but her. Have not been able to replicate the "wander away" error again.

**Comment by CallMeFoxie** [comment]
RE "Abigail Loves You" -- is that "True Love Abigail Dialogue Expansion"?

**Comment by CallMeFoxie** [comment]
Actually Immersive Spouses ... sounds like it could trigger (d'uh) only on spouse, wonder if that's causing something?

**Comment by CallMeFoxie** [comment]
Also, is Abigail just your girlfriend (10hearts) or your wife? They may have added something regarding schedules on married or girlfriend people...

**Comment by purrplingcat** [comment]
Impossible fix it for me. SDV 1.5 changed so many things in NPC code and breaks core of NA. I will retire NPC Adventures from 1st January 2021 and recommend not use this mod anymore.
