### ISSUE TITLE
[BUG] I can't use companions in the volcano

### ISSUE THREAD

**Issue by Linau1** [purrplingcat/NpcAdventures#168]
**Describe the bug**
I recruited HArvey as my companion and I came to ginger island and entered the volacno. I created a bridge but he can't pass it.

**To Reproduce**
1. Go to Ginger island with Harvey
2. Enter to the volcano
3. Create a bridge
4. He won't be able to pass

**Expected behavior**
He shouid've pass the bridge and enter with me

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SDV version 1.5
 - SMAPI version3.8.1
 - Version 0.16.0

**Comment by purrplingcat** [comment]
Mod is dead, won't fix. Mod disapears from Nexusmods 1st January 2021
