### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ra1nbr0** [purrplingcat/NpcAdventures#169]
When I attempted to download using the Nexus Mod Downloader, it says there is an error and it cannot be downloaded, as there is no manifest.json file

To reproduce, you really just have to download it and attempt to either open SMAPI and have it tell you it cannot be opened or use the Nexus Mod Downloader, Vortex and it will not download. 

I expected it to download correctly.

[https://ibb.co/PtHxpr0](url) Here is the screenshot of what it says.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SDV version 1.5
 - SMAPI version 3.10.1
 - Version 0.16.1

**Comment by purrplingcat** [comment]
No issu for me, because Mexusmods downloader is non-transparent and there are no logs. I have no idea how to fix it and why it cannot be downloaded by nexusmods manager. Please download the mod in the manual way.
