### ISSUE TITLE
Birthday Dialogues

### ISSUE THREAD

**Issue by Smirkii** [purrplingcat/NpcAdventures#4]
Specific and unique lines for NPC's birthday

---

As **Player**
I want **birthday variation of dialogues for companion NPC**
I could **dialogues, where NPC say on theirs bday when I recruit them**

**Comment by purrplingcat** [comment]
I created user story #5 of your concept. I implement it in one of next versions :)

**Comment by purrplingcat** [comment]
Reopen and consolidated with #5

**Comment by purrplingcat** [comment]
Discontinued
