### ISSUE TITLE
Mage abilities

### ISSUE THREAD

**Issue by Caco-o-sapo** [purrplingcat/NpcAdventures#59]
**MAGE CLASS** 

The mage npcs are who have some type of connection with magic.

Like: The mage, Krobus, Dwarf and maybe Abigail? (You know what I mean)

They abilities can be:

1. Teleport to some places
2. Protection magic
3. Magics that push away monsters (this is a battle magic, so no cost)
Or anything else.

The magic will have costs to be used, or else this will be too op.
The costs can be items or money, like:

An teleport will cost one quartz or something similar.
 And you could see the magics a available on a simple menu or an HUD.
 Things to do:
- [ ] Create the mage class
- [ ] Add some abilities
- [ ] Add the costs
- [ ] (optional) Make a different way to ask them to go with you. Not by Marlon.

**Comment by purrplingcat** [comment]
Discontinued
